Thrustlb = 12000;
Height = 15;
Velocity = 100;
Pint4 = 1000;
TOperation = 1023;
i_denVec = zeros(20,1); %Initialize vector for current densities
PnetVec = zeros(20,1)'; %Initialize vector for net power generated
Preq = ThrustV4(Thrustlb,Height,Velocity); %Uses the Thrust function to determine net power required per propeller/fan
PdenVec = zeros(20,1)'; %Initialize power density vector
WeightFCVec = zeros(20,1)';
WeightHXVec = zeros(20,1)';
TF1 = 18;
PF1 = Pint4;
PF2 = Pint4;
HF1 = refpropm('H','T',TF1,'P',PF1,'HYDROGEN')/1000; 
TO1 = TOperation;
PO1 = 75;
HO1 = refpropm('H','T',TO1,'P',PO1,'OXYGEN')/1000; %Enthalpy of permeate O2 stream
PO2 = PO1;
PO3 = Pint4; 
CompEff = 0.85;
TA3 = TOperation;
TA4 = TA3;
PA3 = Pint4;
PA4 = PA3;
HA3 = refpropm('H','T',TA3,'P',PA3,'OXYGEN','NITROGEN',[0.21,0.79])/1000; 
HA4 = HA3;
for z = 1:20
    i_den = z/10;
   
[flowO2FC,mFlowH2in,Qgen,PFC,QE1_2,QF3_4,QE4_F3,Cells,TE2,HE2,TE3,HE3,TE5,HE4,TF3] = FCV4(Preq,TOperation,Pint4,i_den); %Required air flow, power and heat generated by the FC based on power required
[Pintake,PA1,TA1,HA1,PA2,TA2,PA5,TA5,HA5,HA2,WC1,PT1,QA2_3,mAirIn,Membrane] = OTMV3(QE1_2,flowO2FC,Height,Velocity,PO1); %Net power generated or consumed by the compressor/OTM/turbine intake cycle  
[QO1_2,WC2,TO2] = Comp2(TOperation,PO1,PO3,CompEff,flowO2FC); %Recompression of pure O2 stream and required heat rejection 
[Pden,WeightHX,WeightCompressor,WeightTurbine,WeightFC,WeightOTM,WeightSystem] = WeightV4(QE1_2,QO1_2,QF3_4,QE4_F3,WC2,Preq,PT1,WC1,Cells,Membrane);
[WBlower,TF4,HF4] = Blower(mFlowH2in,Pint4);
Pnet = PFC + Pintake - WC2  - WBlower; 
i_denVec(z) = i_den;
PnetVec(z) = Pnet;
PdenVec(z) = Pden;
WeightHXVec(z) = WeightHX/WeightSystem;
WeightFCVec(z) = WeightFC/WeightSystem; 
end
% plot(i_denVec,WeightHXVec,i_denVec,WeightFCVec)
% hold on
plot(i_denVec,PdenVec)
flowO2FC
%StateTable = [TA1 PA1; TA2 PA2; TA3 PA3; TA4 PA4; TA5 PA5; TF1 PF1; TF2 PF2; TF3 PF3; TF4 PF4; TF5 PF5; TO1 PO1; TO2 PO2; TO3 PO3; TE1 PE1; TE2 PE2; TE3 PE3; TE4 PE4]
