function [FC,cath_out,anode_out] = std_fuelcell(options,cath_in,anode_in)
%% determine operating conditions (fuel flow) that results in the specified temperature gradient
F = 96485.33; %Faraday's Constant in Coulombs/mol
Ru = 8.314; %Universal gas constant, J/mol.K  
T = options.T_fc;
P = cath_in.P;
[n1,n2] = size(T);
W = 9; %Width of active cell area in cm
L = 9; %Length of active cell area in cm
n = 10; %Number of nodes at which the voltage change is calculated
FC.cell_area = W*L;
FC.Cells = options.SOFC_area.*10000/FC.cell_area; % Number of cells based on total active surface area of 81 cm^2 per cell
dH = 0*T;
for i = 1:1:n2
%     dS(:,i) = refproparray('s','T',T(:,i),'P',P(:,i),'WATER')*18.01528 - refpropm('s','T',T(:,i),'P',P(:,i),'Hydrogen')*2.016 - .5*refpropm('s','T',T(:,i),'P',P(:,i),'Oxygen')*32;
    dH(:,i) = refproparray('h','T',T(:,i),'P',P(:,i),'WATER')*18.01528 - refproparray('h','T',T(:,i),'P',P(:,i),'Hydrogen')*2.016 - .5*refproparray('h','T',T(:,i),'P',P(:,i),'Oxygen')*32 - 45839000 - 241826400;%J/kmol
end
% E0 = -(dH-T.*dS)/(2000*F)%Reference Voltage
FC.G = -198141 + (T-900)*(-192652+198141)/(1000-900);
FC.G(T>1000) = -192652 + (T(T>1000)-1000)*(-187100+192652)/(1100-1000);
E0 = -FC.G/(2*F);

J_int = zeros(n1,n2,n); %Initializing the matrix for Current distribution
FC.hrxnmol = -dH/1000; %H2 + 0.5*O2 -->  H2O, Heat Released in kJ/kmol

anode_out = anode_in;
FC.H2_supply = anode_in.H2;
FC.H2O_supply = anode_in.H2O;
FC.H2_used = anode_in.H2.*options.spu;
FC.i_total = FC.H2_used*2000*F; %Flow of H2 that reacts
FC.n_in = net_flow(anode_in); 
anode_out.T = anode_in.T + options.dT_fc;
anode_out.H2 = anode_in.H2 - FC.H2_used;
anode_out.H2O = anode_in.H2O + FC.H2_used; %Water/Steam Produced by Reaction, mol/s

V =  E0 + Ru*T./(2*F).*log(.85*.15/.15.*(P/100).^0.5) - FC.i_total./(1e4*options.SOFC_area).*options.asr;%estimate of V
FC.Qgen =  FC.hrxnmol.*FC.i_total./(2000.*F) - V.*FC.i_total./1000; %Heat generated by fuel cell, kW 
i = (ones(n1,n2,n)).*(FC.i_total./(1e4.*options.SOFC_area)); %Initial current density distribution per cell
Vold = V;
asr = zeros(n1,n2,n);
for j = 1:1:n
    asr(:,:,j) = options.asr;
end
X_H2 = zeros(n1,n2,n);   
X_H2O = zeros(n1,n2,n);
X_O2 = zeros(n1,n2,n);
E = zeros(n1,n2,n);

ion.T = options.T_fc;
ion.P = P; 
ion.O2 = FC.H2_used/2;
Q_ion = property(ion,'h','kJ');
Q_cath_in = property(cath_in,'h','kJ');
cath_not_bypass = cath_in;
cath_not_bypass.T = options.T_fc + .5*options.dT_fc;

max_bypass = (1-ion.O2./cath_in.O2);
bypass = 0;
error_V = 1;
while any(any(abs(error_V)>1e-4))
    for k=1:1:n
        J_int(:,:,k) = sum(i(:,:,1:k),3).*(FC.cell_area/n); %integral of current density as a function of length, total current thus far
        X_H2(:,:,k) = (FC.H2_supply - J_int(:,:,k)./(2000*F./FC.Cells))./(FC.n_in); %Concentration of H2 as a function of position and steam concentration
        X_H2O(:,:,k) = 1-X_H2(:,:,k); %Concentration of H20 product as H2 is consumed 
        X_O2(:,:,k) = (cath_in.O2.*(1-bypass) - J_int(:,:,k)./(4000*F./FC.Cells))./(net_flow(cath_in).*(1-bypass) - J_int(:,:,k)./(4000*F./FC.Cells));
        E(:,:,k) = E0 + Ru*T./(2*F).*log(X_H2(:,:,k).*X_O2(:,:,k)./(X_H2O(:,:,k).*(P/100).^0.5)); %Nernst Potential as a function of product and reactant concentrations
    end
    error = max(max(FC.i_total));
    while any(any(abs(error)>(FC.i_total*1e-4))) 
        i = max(0,E-V.*ones(1,1,n))./asr; %new current distribution
        error = (sum(i,3).*options.SOFC_area*1e4/n) - FC.i_total; %error in total current
        error(isnan(error)) = 0;
        error(isinf(error)) = 0;
        V = min(1.4,max(.2,V + .4*(error./options.SOFC_area/1e4.*options.asr))); %New average voltage 
    end  
    error_V = Vold - V;
    Vold = V;
    
    %% adjust bypass to ensure deltaT
    FC.Qgen =  FC.hrxnmol.*FC.i_total./(2000.*F) - V.*FC.i_total./1000; %Heat generated by fuel cell, kW 
    FC.Q_anode = property(anode_out,'h','kJ') - property(anode_in,'h','kJ') - Q_ion; %heat removed by anode (kW)
    Q_cath = FC.Qgen - FC.Q_anode;
    
    cath_not_bypass.O2 = cath_in.O2.*(1-bypass) - ion.O2;
    cath_not_bypass.N2 = cath_in.N2.*(1-bypass);
    Q_need = property(cath_not_bypass,'h','kJ') + Q_ion - Q_cath_in.*(1-bypass);
    error_Q = (Q_need - Q_cath)./max(Q_cath,Q_need);
%     bypass = bypass + (bypass==0).*(error_Q>0).*.05;
    bypass = min(.99*max_bypass,max(0,bypass + max(0.5*error_Q,-(max_bypass-bypass).*(-error_Q))));
end

cath_out = cath_in;
cath_out.O2 = max(1e-3*cath_in.O2,cath_in.O2 - ion.O2);
cath_out.T = find_T(cath_out, property(cath_in,'h','kJ') + Q_cath - Q_ion);

FC.V = V;
FC.Power = FC.V.*FC.i_total./1000; %Electric Power produced by FC, kW
FC.O2 = ion.O2;
FC.i_den = FC.i_total./(options.SOFC_area*10000); %A/cm^2
FC.i_Cell = FC.cell_area*FC.i_den;%FC.i_total./FC.Cells; %Total amount of current per cell
FC.pressure = P;
FC.bypass = bypass;
end