function [FC,E1] = FuelCell_H2(T,ASR,A1,L,W,n,Cells,P,O2util,util,r,options)
%%Elcogen: iDen = 0.0882 A/cm^2, L = 0.17m, W = 0.2m, oxidant util = 22%
Ru = 8.314;
F = 96485; %Faraday constant C/mol
J = A1.O2*O2util*4000*F; %Total current based on 02 utilization; 
iDen = J./(L*W*Cells); % total current in A
V = .85*ones(length(A1.O2),1);
%%Initial guesses
Fuel.H2 = J/(2000*F*options.spu(1,1)); %flow rate in kmol/sec
% h = enthalpy(T);
% s = entropy(T);
%E0 = -((h.H2O-s.H2O.*T)-(h.H2-s.H2.*T)-.5*(h.O2-s.O2.*T))/(2*F); %reference voltage
T_avg = T + .5*options.dT_fc;
nine_to_hundred = (T_avg>=900 & T_avg < 1000);
FC.G = -198141 + (T_avg-900)*(-192652+198141)/(1000-900);
FC.G(~nine_to_hundred) = -192652 + (T_avg(~nine_to_hundred)-1000)*(-187100+192652)/(1100-1000);
FC.G0 = -228608; %Enthalpy of formation for water at 298K & 100 kPa, kJ/kmol;
E0 = -FC.G/(2*F);

h_H2O = (refproparray('h','T',T,'P',P,'WATER')*18/1000 -45839 -241847);% total enthalpy in kJ/kmol
h_H2 = ((refproparray('h','T',T,'P',P,'hydrogen') - refpropm('h','T',298,'P',100,'hydrogen'))*2/1000);% total enthalpy in kJ/mol
h_O2 = ((refproparray('h','T',T,'P',P,'oxygen') - refpropm('h','T',298,'P',100,'oxygen'))*32/1000);% total enthalpy in kJ/kmol
% s_H2O = ((refpropm('s','T',T,'P',P,'WATER') - refpropm('s','T',298,'P',100,'WATER'))*18/1000 -44010 -241847);% total enthalpy in kJ/kmol
% s_H2 = ((refpropm('s','T',T,'P',P,'hydrogen') - refpropm('s','T',298,'P',100,'hydrogen'))*2/1000);% total enthalpy in kJ/kmol
% s_O2 = ((refpropm('s','T',T,'P',P,'oxygen') - refpropm('s','T',298,'P',100,'oxygen'))*32/1000);% total enthalpy in kJ/kmol
hrxn = -(h_H2O - h_H2 - .5*h_O2); %H2 + 0.5*O2 -->  H2O, Heat Released in kJ/kmol
FC.hrxnmol = hrxn(1,1); 
%solve for distribution
i = ((J./(Cells.*L.*W)*ones(1,n))); %Initial current distribution per cell
H2consume = zeros(length(i(:,1)),n);
X_H2 = zeros(length(i(:,1)),n);
X_O2 = zeros(length(i(:,1)),n);
X_H2O = zeros(length(i(:,1)),n);

H2in = Fuel.H2 + (Fuel.H2 - J/(2000*F)).*r./(1-r);
N2in = 0;%.*r./(1-r);
H2Oin = 0.05*H2in; % 5% Fuel Humidification
FlowIn = H2in+H2Oin+N2in;

O2start = A1.O2;
error = 1;
% J = 0.01;
while abs(error)>1e-5
    for k=1:1:n
        H2consume(:,k) = Cells.*sum(i(:,1:k),2)*L*W/n/(2000*F); %hydrogen consumption since start of cell
        X_H2(:,k) = max(1e-4,(H2in-H2consume(:,k))./FlowIn);
        X_H2O(:,k) = min(1,max(3e-3,(H2Oin+H2consume(:,k))./FlowIn));
        X_O2(:,k) = (O2start - .5*H2consume(:,k))./(NetFlow(A1)-0.5*H2consume(:,k));
    end

    E = E0*ones(1,n) + Ru*(T*ones(1,n))./(2*F).*log(X_H2.*X_O2.^.5./X_H2O.*(P*ones(1,n)).^.5);%Nernst Potential
    i = max(0,(E-V*ones(1,n))./(ASR*ones(1,n)));%new current distribution
    error = ((sum(i,2)/n - J./(Cells*L*W)).*ASR);
    i = max(0,(E-(V+error)*ones(1,n))./(ASR*ones(1,n)));%new current distribution
    i = i.*(J./(Cells.*L.*W)./mean(i,2)*ones(1,n));
    V = V + 0.5*min(min(E,[],2)-V,error);
end
FC.FuelFlow = Fuel.H2;
FC.H2used = options.spu(1,1)*Fuel.H2;
FC.hrxnmol = (-(h_H2O - h_H2 - h_O2)); %Heat of reaction per kmol of H2O formation
FC.H2Oin = H2Oin;
FC.Flow.T = T;
FC.O2out = A1.O2*(1-O2util);
FC.Flow.H2 = X_H2(:,end).*FlowIn.*(1-r);
FC.Flow.H2O = X_H2O(:,end).*FlowIn.*(1-r);
FC.H2concentration = X_H2(:,end);
FC.Utilization = J/(2000*F)./(Fuel.H2); %actual H2 use in kmol/s divided by ideal H2 production in kmol/s
FC.Power = (V*J)/1000;
FC.Efficiency = FC.Power./(FC.H2used.*(FC.hrxnmol)); %Lower heating value of H2
FC.Qgen = FC.H2used.*(FC.hrxnmol) - FC.Power; %Heat Generated by FC
FC.Recirculation = r;
FC.N2out = A1.N2; 
FC.Voltage = V;
FC.iDen = iDen; 
FC.H2used = J/(2000*F);
FC.Current = J;
FC.SPU = (H2in-X_H2(:,end).*FlowIn)./H2in;
E1.T = T + 25;
E1.P = 980;
E1.H2 = FC.Flow.H2;
E1.H2O = FC.Flow.H2O;
