function [Weight,param] = NetParam_2(options,FCArray,intake,HL)
Ein = FCArray.H2used.*FCArray.hrxnmol; %Lower heating value of fuel intake, kJ/kmol
Eout = FCArray.Power + intake.C1_work + HL.blower_work + intake.T1_work;
param.FTE = Eout./Ein;
param.FC_eff = FCArray.Power./Ein;
param.FCPower = FCArray.Power;
param.NetPower = Eout;
param.Cells = FCArray.Cells; 
param.O2used = 0.21*options.airflow - FCArray.O2out;
param.O2util = FCArray.O2util;
param.preheat_air = intake.heat_added; 
param.FCVoltage = FCArray.FCVoltage;
param.Qgen = FCArray.Qgen;
param.Qremovefuel = HL.Qremove_fuel; 
param.Qoutanode = HL.Qoutanode;
param.Qoutcathode = HL.Qoutcathode;
param.H2_used = FCArray.H2used; 
[Weight] = weight_2(options,param,FCArray,intake,HL);
param.weight = Weight.Total;
param.weightComp = Weight.comp;
param.weightTurb = Weight.turb;
param.weightFC = Weight.sofc; 
param.weightHX = Weight.hx; 
param.iden = FCArray.iDenArray;
param.C1_work = intake.C1_work;
param.T1_work = intake.T1_work; 
param.hrxnmol = FCArray.hrxnmol;
param.Qbalance = HL.Qexcess;
param.BlowerWork = HL.blower_work;
param.P_den = Eout./param.weight;

end

%    O2util =  i*0.035;
%         Cells = 100000 + 10000*j;
%         [FC,E1] = FuelCell_H2(T,ASR,A1,L,W,n,Cells,P,O2util,util,r);
%         FCArray.Power(i,j) = FC.Power;
%         FCArray.Qgen(i,j) = FC.Qgen;
%         FCArray.Efficiency(i,j) = FC.Efficiency;
%         FCArray.H2in(i,j) = FC.FuelFlow;
%         FCArray.H2out(i,j) = FC.Flow.H2;
%         FCArray.H2Oout(i,j) = FC.Flow.H2O;
%         FCArray.iDenArray(i,j) = FC.iDen;
%         FCArray.CellsArray(i,j) = Cells;
%         FCArray.FCVoltage(i,j) = FC.Voltage;
%         FCArray.O2out(i,j) = FC.O2out; 
%         FCArray.N2out(i,j) = FC.N2out; 
%         FCArray.H2used(i,j) = FC.H2used;
%         FCArray.E1H2(i,j) = E1.H2; 
%         FCArray.E1H2O(i,j) = E1.H2O; 
%         FCArray.H2Oin(i,j) = FC.H2Oin; 